/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.ArrayList;
import java.util.Iterator;
import base.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Jempol
 */
public class FrameAdmin extends javax.swing.JFrame {
    private User user = new User();
    private User Admin = new User();
    private Mahasiswa mahasiswa = new Mahasiswa();
    private Dosen dosen = new Dosen();
    private Prodi prodi = new Prodi();
   

    /**
     * Creates new form FrameAdmin
     */
    public FrameAdmin() {
        initComponents();
        hideShowId(false);
        hideShowAll(false);
        tglLahir.setDateFormatString("dd-MM-yyyy");
        setComboxAll();
        initComponents();
    }
    public FrameAdmin(User Admin) {
        super("Admin : " + Admin.getusername());
        setAdmin(Admin);
        initComponents();
        hideShowId(false);
        hideShowAll(false);
        tglLahir.setDateFormatString("dd-MM-yyyy");
        setComboxAll();
    }
    public void hideShowAll(boolean bool){
        kataSandiLabel.setVisible(bool);
        kataSandiTextField.setVisible(bool);
        namaLabel.setVisible(bool);
        namaTextField.setVisible(bool);
        nikLabel.setVisible(bool);
        nikTextField.setVisible(bool);
        tglLahirLabel.setVisible(bool);
        tglLahir.setVisible(bool);
        jKLabel.setVisible(bool);
        LRadioButton.setVisible(bool);
        PRadioButton.setVisible(bool);
        alamatLabel.setVisible(bool);
        alamatTextField.setVisible(bool);
        emailLabel.setVisible(bool);
        emailTextField.setVisible(bool);
        agamaLabel.setVisible(bool);
        agamaComboBox.setVisible(bool);
        prodiLabel1.setVisible(bool);
        prodiComboBox.setVisible(bool);
        dsnPembLabel.setVisible(bool);
        dsnComboBox.setVisible(bool);
        updateButton.setVisible(bool);
        simpanButton.setVisible(bool);
    }
    
    public void hideShowId(boolean bool){
        id.setVisible(bool);
        idTextField.setVisible(bool);
        cariButton.setVisible(bool);
    }
    public void setDosenCombox(ArrayList<Dosen> list){
        Iterator<Dosen> tiapList = list.iterator();
        
        while(tiapList.hasNext()){
            Dosen d = tiapList.next();
            dsnComboBox.addItem(d.getnama());
        }  
    }
    
    public void setProdiCombox(ArrayList<Prodi> list){
        Iterator<Prodi> tiapList = list.iterator();
        
        while(tiapList.hasNext()){
            Prodi p = tiapList.next();
            prodiComboBox.addItem(p.getnamaProdi());
        }  
    }
    
    public void setComboxAll(){
        prodiComboBox.removeAllItems();
        prodiComboBox.addItem("-Jurusan-");
        dsnComboBox.removeAllItems();
        dsnComboBox.addItem("-Dosen Pembimbing-");
     setProdiCombox(getProdi().semuaDB());
     setDosenCombox(getDosen().semuaDB());
    }
    
    public void setDefaultTeksField(){
        kataSandiTextField.setText("Password " + opsiComboBox.getSelectedItem().toString());
        namaTextField.setText("Nama " + opsiComboBox.getSelectedItem().toString());
        nikTextField.setText("Nik " + opsiComboBox.getSelectedItem().toString());
        alamatTextField.setText("Alamat " + opsiComboBox.getSelectedItem().toString());
        emailTextField.setText("Email " + opsiComboBox.getSelectedItem().toString());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                opsiComboBox = new javax.swing.JComboBox<>();
                idTextField = new javax.swing.JTextField();
                kataSandiTextField = new javax.swing.JTextField();
                namaTextField = new javax.swing.JTextField();
                nikTextField = new javax.swing.JTextField();
                tglLahir = new com.toedter.calendar.JDateChooser();
                LRadioButton = new javax.swing.JRadioButton();
                alamatTextField = new javax.swing.JTextField();
                emailTextField = new javax.swing.JTextField();
                agamaComboBox = new javax.swing.JComboBox<>();
                prodiComboBox = new javax.swing.JComboBox<>();
                dsnComboBox = new javax.swing.JComboBox<>();
                updateButton = new javax.swing.JButton();
                simpanButton = new javax.swing.JButton();
                logoutButton = new javax.swing.JButton();
                cariButton = new javax.swing.JButton();
                PRadioButton = new javax.swing.JRadioButton();
                id = new javax.swing.JLabel();
                kataSandiLabel = new javax.swing.JLabel();
                namaLabel = new javax.swing.JLabel();
                nikLabel = new javax.swing.JLabel();
                tglLahirLabel = new javax.swing.JLabel();
                jKLabel = new javax.swing.JLabel();
                alamatLabel = new javax.swing.JLabel();
                emailLabel = new javax.swing.JLabel();
                agamaLabel = new javax.swing.JLabel();
                prodiLabel1 = new javax.swing.JLabel();
                dsnPembLabel = new javax.swing.JLabel();
                backgroud = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                opsiComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih --", "Prodi", "Dosen", "Mahasiswa" }));
                opsiComboBox.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                opsiComboBoxActionPerformed(evt);
                        }
                });
                getContentPane().add(opsiComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 150, -1));

                idTextField.setText("id");
                getContentPane().add(idTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 180, 30));

                kataSandiTextField.setText("kata sandi");
                getContentPane().add(kataSandiTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 180, 30));

                namaTextField.setText("nama");
                getContentPane().add(namaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 180, 30));

                nikTextField.setText("nik");
                getContentPane().add(nikTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 180, 30));

                tglLahir.setToolTipText("dd-MM-YYYY");
                getContentPane().add(tglLahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 150, 30));

                LRadioButton.setText("L");
                getContentPane().add(LRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, -1, -1));

                alamatTextField.setText("alamat");
                getContentPane().add(alamatTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 180, 50));

                emailTextField.setText("email");
                getContentPane().add(emailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 500, 180, 30));

                agamaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ISLAM", "KRISTEN", "KATOLIK", "HINDU", "BUDHA", "KONGHUCU" }));
                getContentPane().add(agamaComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 540, 130, 20));

                prodiComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih Prodi-" }));
                getContentPane().add(prodiComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 580, 110, -1));

                dsnComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih Dosen Wali-" }));
                dsnComboBox.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                dsnComboBoxActionPerformed(evt);
                        }
                });
                getContentPane().add(dsnComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 620, -1, -1));

                updateButton.setText("UPDATE");
                updateButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                updateButtonActionPerformed(evt);
                        }
                });
                getContentPane().add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 680, -1, -1));

                simpanButton.setText("SIMPAN");
                simpanButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                simpanButtonActionPerformed(evt);
                        }
                });
                getContentPane().add(simpanButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 680, -1, -1));

                logoutButton.setText("LOGOUT");
                logoutButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                logoutButtonActionPerformed(evt);
                        }
                });
                getContentPane().add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 680, -1, -1));

                cariButton.setText("Cari");
                cariButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cariButtonActionPerformed(evt);
                        }
                });
                getContentPane().add(cariButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, -1, -1));

                PRadioButton.setText("P");
                getContentPane().add(PRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, -1, -1));

                id.setText("ID Prodi");
                getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

                kataSandiLabel.setText("Kata Sandi");
                getContentPane().add(kataSandiLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

                namaLabel.setText("Nama");
                getContentPane().add(namaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));

                nikLabel.setText("NIK");
                getContentPane().add(nikLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, -1));

                tglLahirLabel.setText("Tanggal Lahir");
                getContentPane().add(tglLahirLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, -1, -1));

                jKLabel.setText("Jenis Kelamin");
                getContentPane().add(jKLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, -1, -1));

                alamatLabel.setText("Alamat");
                getContentPane().add(alamatLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, -1, -1));

                emailLabel.setText("E-Mail");
                getContentPane().add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 500, -1, -1));

                agamaLabel.setText("Agama");
                getContentPane().add(agamaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 540, -1, -1));

                prodiLabel1.setText("Prodi");
                getContentPane().add(prodiLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 580, -1, -1));

                dsnPembLabel.setText("Dosen Wali");
                getContentPane().add(dsnPembLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 620, -1, -1));
                getContentPane().add(backgroud, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 87, 561, 811));

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void opsiComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opsiComboBoxActionPerformed
        // TODO add your handling code here:
        hideShowAll(true);
        setComboxAll();
        switch (opsiComboBox.getSelectedItem().toString()){
            case "-- pilih --" :
            {
                hideShowId(false);
                break;
            }
            default :
            {
                hideShowId(true);
                id.setText("ID " + opsiComboBox.getSelectedItem());
                namaLabel.setText("Nama " + opsiComboBox.getSelectedItem());
            }
            setDefaultTeksField();
        }
    }//GEN-LAST:event_opsiComboBoxActionPerformed

    private void dsnComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dsnComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dsnComboBoxActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:

        switch (opsiComboBox.getSelectedItem().toString()){
            case "Mahasiswa" :
            {
                getUser().setusername(idTextField.getText());
                getUser().setpassword(kataSandiTextField.getText());
                getUser().settipeUser(opsiComboBox.getSelectedItem().toString());
                getUser().updateDB();

                getMahasiswa().setnim(idTextField.getText());

                getMahasiswa().dosen = null;
                getMahasiswa().prodi = null;
                if(dsnComboBox.getSelectedIndex() != 0)
                {
                    getMahasiswa().dosen = new Dosen().satuDB(dsnComboBox.getSelectedItem().toString());
                }

                if(prodiComboBox.getSelectedIndex() != 0)
                {
                    getMahasiswa().prodi = new Prodi().satuDB(prodiComboBox.getSelectedItem().toString());
                }

                getMahasiswa().setnama(namaTextField.getText());
                getMahasiswa().setnik(nikTextField.getText());
                getMahasiswa().settanggalLahir(tglLahir.getDate());
                getMahasiswa().setjenisKelamin((LRadioButton.isSelected())? "L" : "P");
                getMahasiswa().setalamat(alamatTextField.getText());
                getMahasiswa().setemail(emailTextField.getText());
                getMahasiswa().setagama(agamaComboBox.getSelectedItem().toString());

                getMahasiswa().updateDB();
                break;
            }

            case "Dosen" :
            {
                getUser().setusername(idTextField.getText());
                getUser().setpassword(kataSandiTextField.getText());
                getUser().settipeUser(opsiComboBox.getSelectedItem().toString());
                getUser().masukDB();

                getDosen().setnidn(idTextField.getText());
                getDosen().setnama(namaTextField.getText());
                getDosen().setnik(nikTextField.getText());
                getDosen().settanggalLahir(tglLahir.getDate());
                getDosen().setjenisKelamin((LRadioButton.isSelected())? "L" : "P");
                getDosen().setalamat(alamatTextField.getText());
                getDosen().setemail(emailTextField.getText());
                getDosen().setagama(agamaComboBox.getSelectedItem().toString());

                getDosen().updateDB();
                break;
            }

            case "Prodi" :
            {
                getUser().setusername(idTextField.getText());
                getUser().setpassword(kataSandiTextField.getText());
                getUser().settipeUser(opsiComboBox.getSelectedItem().toString());
                getUser().masukDB();

                getProdi().setidProdi(idTextField.getText());
                getProdi().setnamaProdi(namaTextField.getText());

                getProdi().updateDB();
                break;
            }
        }
        JOptionPane.showMessageDialog(null, "Data Sudah di update");
        opsiComboBox.setSelectedIndex(0);
    }//GEN-LAST:event_updateButtonActionPerformed

    private void simpanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanButtonActionPerformed
         
        switch (opsiComboBox.getSelectedItem().toString()){
            case "Mahasiswa" :
            {
                getUser().setusername(idTextField.getText());
                getUser().setpassword(kataSandiTextField.getText());
                getUser().settipeUser(opsiComboBox.getSelectedItem().toString());
                getUser().masukDB();

                getMahasiswa().setnim(idTextField.getText());

                if(dsnComboBox.getSelectedIndex() != 0)
                {
                    getMahasiswa().dosen = new Dosen().satuDB(dsnComboBox.getSelectedItem().toString());
                }

                if(prodiComboBox.getSelectedIndex() != 0)
                {
                    getMahasiswa().prodi = new Prodi().satuDB(prodiComboBox.getSelectedItem().toString());
                }

                getMahasiswa().setnama(namaTextField.getText());
                getMahasiswa().setnik(nikTextField.getText());
                getMahasiswa().settanggalLahir(tglLahir.getDate());
                getMahasiswa().setjenisKelamin((LRadioButton.isSelected())? "L" : "P");
                getMahasiswa().setalamat(alamatTextField.getText());
                getMahasiswa().setemail(emailTextField.getText());
                getMahasiswa().setagama(agamaComboBox.getSelectedItem().toString());

                getMahasiswa().masukDB();
                break;
            }

            case "Dosen" :
            {
                getUser().setusername(idTextField.getText());
                getUser().setpassword(kataSandiTextField.getText());
                getUser().settipeUser(opsiComboBox.getSelectedItem().toString());
                getUser().masukDB();

                getDosen().setnidn(idTextField.getText());
                getDosen().setnama(namaTextField.getText());
                getDosen().setnik(nikTextField.getText());
                getDosen().settanggalLahir(tglLahir.getDate());
                getDosen().setjenisKelamin((LRadioButton.isSelected())? "L" : "P");
                getDosen().setalamat(alamatTextField.getText());
                getDosen().setemail(emailTextField.getText());
                getDosen().setagama(agamaComboBox.getSelectedItem().toString());

                getDosen().masukDB();
                break;
            }

            case "Prodi" :
            {
                getUser().setusername(idTextField.getText());
                getUser().setpassword(kataSandiTextField.getText());
                getUser().settipeUser(opsiComboBox.getSelectedItem().toString());
                getUser().masukDB();

                getProdi().setidProdi(idTextField.getText());
                getProdi().setnamaProdi(namaTextField.getText());

                getProdi().masukDB();
                break;
            }
        }
        JOptionPane.showMessageDialog(null, "Data Sudah di simpan");
        opsiComboBox.setSelectedIndex(0);
    }//GEN-LAST:event_simpanButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
         
        new login_user().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void cariButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariButtonActionPerformed
         
        setComboxAll();
        setUser(new User());
        setMahasiswa(new Mahasiswa());
        setDosen(new Dosen());
        setProdi(new Prodi());
        setDefaultTeksField();
        switch (opsiComboBox.getSelectedItem().toString()){
            case "Mahasiswa" :
            {
                setUser(new User().satuDB(idTextField.getText()));
                setMahasiswa(new Mahasiswa().satuDB(idTextField.getText()));
                if ((getMahasiswa().getnama() == null) || (getMahasiswa().getnama() == "") || (getMahasiswa().getnama() == "id")){
                    hideShowAll(true);
                    updateButton.setVisible(false);
                }
                else
                {
                    hideShowAll(true);
                    simpanButton.setVisible(false);
                    kataSandiTextField.setText(getUser().getpassword());
                    namaTextField.setText(getMahasiswa().getnama());
                    nikTextField.setText(getMahasiswa().getnik());
                    tglLahir.setDate(getMahasiswa().gettanggalLahir());
                    if (getMahasiswa().getjenisKelamin().charAt(0) == 'L') {
                        LRadioButton.setSelected(true);
                    }
                    else
                    {
                        PRadioButton.setSelected(true);
                    }
                    alamatTextField.setText(getMahasiswa().getalamat());
                    emailTextField.setText(getMahasiswa().getemail());
                    agamaComboBox.setSelectedItem(getMahasiswa().getagama());
                    if(getMahasiswa().dosen != null)
                    {
                        dsnComboBox.setSelectedItem(getMahasiswa().dosen.getnama());
                    }
                    if(getMahasiswa().prodi != null)
                    {
                        prodiComboBox.setSelectedItem(getMahasiswa().prodi.getnamaProdi());
                    }
                }
            
                break;
        
            }

            case "Dosen" :
            {
                setUser(new User().satuDB(idTextField.getText()));
                setDosen(new Dosen().satuDB(idTextField.getText()));
                if ((getDosen().getnama() == null) || (getDosen().getnama() == "") || (getDosen().getnama() == "id")){
                    hideShowAll(true);
                    updateButton.setVisible(false);
                    dsnPembLabel.setVisible(false);
                    dsnComboBox.setVisible(false);
                }
                else
                {
                    hideShowAll(true);
                    dsnPembLabel.setVisible(false);
                    dsnComboBox.setVisible(false);
                    simpanButton.setVisible(false);
                    kataSandiTextField.setText(getUser().getpassword());
                    namaTextField.setText(getDosen().getnama());
                    nikTextField.setText(getDosen().getnik());
                    tglLahir.setDate(getDosen().gettanggalLahir());
                    if (getDosen().getjenisKelamin().charAt(0) == 'L') {
                        LRadioButton.setSelected(true);
                    }
                    else
                    {
                        PRadioButton.setSelected(true);
                    }
                    alamatTextField.setText(getDosen().getalamat());
                    emailTextField.setText(getDosen().getemail());
                    agamaComboBox.setSelectedItem(getDosen().getagama());
                }
                break;
            
            }
            case "Prodi" :
            {
                setUser(new User().satuDB(idTextField.getText()));
                setProdi(new Prodi().satuDB(idTextField.getText()));
                if ((getProdi().getnamaProdi() == null) || (getProdi().getnamaProdi() == "") || (getProdi().getnamaProdi() == "id")){
                    hideShowAll(false);
                    kataSandiLabel.setVisible(true);
                    kataSandiTextField.setVisible(true);
                    namaLabel.setVisible(true);
                    namaTextField.setVisible(true);
                    simpanButton.setVisible(true);
                }
                else
                {
                    hideShowAll(false);
                    kataSandiLabel.setVisible(true);
                    kataSandiTextField.setVisible(true);
                    namaLabel.setVisible(true);
                    namaTextField.setVisible(true);
                    kataSandiTextField.setText(getUser().getpassword());
                    namaTextField.setText(getProdi().getnamaProdi());
                    updateButton.setVisible(true);
                }
                break;
            }
    }//GEN-LAST:event_cariButtonActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameAdmin().setVisible(true);
            }
        });
    }
    

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JRadioButton LRadioButton;
        private javax.swing.JRadioButton PRadioButton;
        private javax.swing.JComboBox<String> agamaComboBox;
        private javax.swing.JLabel agamaLabel;
        private javax.swing.JLabel alamatLabel;
        private javax.swing.JTextField alamatTextField;
        private javax.swing.JLabel backgroud;
        private javax.swing.JButton cariButton;
        private javax.swing.JComboBox<String> dsnComboBox;
        private javax.swing.JLabel dsnPembLabel;
        private javax.swing.JLabel emailLabel;
        private javax.swing.JTextField emailTextField;
        private javax.swing.JLabel id;
        private javax.swing.JTextField idTextField;
        private javax.swing.JLabel jKLabel;
        private javax.swing.JLabel kataSandiLabel;
        private javax.swing.JTextField kataSandiTextField;
        private javax.swing.JButton logoutButton;
        private javax.swing.JLabel namaLabel;
        private javax.swing.JTextField namaTextField;
        private javax.swing.JLabel nikLabel;
        private javax.swing.JTextField nikTextField;
        private javax.swing.JComboBox<String> opsiComboBox;
        private javax.swing.JComboBox<String> prodiComboBox;
        private javax.swing.JLabel prodiLabel1;
        private javax.swing.JButton simpanButton;
        private com.toedter.calendar.JDateChooser tglLahir;
        private javax.swing.JLabel tglLahirLabel;
        private javax.swing.JButton updateButton;
        // End of variables declaration//GEN-END:variables
 public User getUser() {
        return user;
    }

    /**
     * @param userFrame the userFrame to set
     */
    public void setUser(User user) {
        this.user = user;
    }

    /**
     * @return the mahasiswa
     */
    public Mahasiswa getMahasiswa() {
        return mahasiswa;
    }

    /**
     * @param mahasiswa the mahasiswa to set
     */
    public void setMahasiswa(Mahasiswa mahasiswa) {
        this.mahasiswa = mahasiswa;
    }

    /**
     * @return the dosen
     */
    public Dosen getDosen() {
        return dosen;
    }

    /**
     * @param dosen the dosen to set
     */
    public void setDosen(Dosen dosen) {
        this.dosen = dosen;
    }

    /**
     * @return the prodi
     */
    public Prodi getProdi() {
        return prodi;
    }

    /**
     * @param prodi the prodi to set
     */
    public void setProdi(Prodi prodi) {
        this.prodi = prodi;
    }

    public User getAdmin() {
        return Admin;
    }

    public void setAdmin(User Admin) {
        this.Admin = Admin;
    }
}
