/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import base.*;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jempol
 */
public class FrameDospem extends javax.swing.JFrame {
    private User user = new User();
    private Dosen dosen = new Dosen();
    private Mahasiswa mahasiswa = new Mahasiswa();
    private KerjaPraktek kerjaPraktek = new KerjaPraktek();
    private PersetujuanDosen persetujuanDosen = new PersetujuanDosen();
    private PersetujuanProdi persetujuanProdi = new PersetujuanProdi();
    private Bimbingan bimbingan = new Bimbingan();
    
    /**
     * Creates new form FrameDospem
     */
    public FrameDospem() {
        initComponents();
    }
     public FrameDospem(User user) {
        super("Dosen : " + (new Dosen().satuDB(user.getusername())).getnama());
        setUser(user);
        setDosen(new Dosen().satuDB(user.getusername()));
        initComponents();
        nidnLabel.setText("NIDN                            : " + getDosen().getnidn());
        namaDosenLabel.setText("Nama Dosen                : " + getDosen().getnama());
	
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                nidnLabel = new javax.swing.JLabel();
                namaDosenLabel = new javax.swing.JLabel();
                mahasiswaLabel = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                tabelBimbing = new javax.swing.JTable();
                konfirmCheckbox = new javax.swing.JCheckBox();
                btn_simpan = new javax.swing.JButton();
                btn_logout = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                nidnLabel.setText("NIDN                            : ");

                namaDosenLabel.setText("Nama Dosen                : ");

                mahasiswaLabel.setText("Mahasiswa Bimbingan : ");

                tabelBimbing.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {

                        },
                        new String [] {
                                "Nama Mahasiswa", "NIM", "Kegiatan", "Instansi KP"
                        }
                ) {
                        Class[] types = new Class [] {
                                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
                        };
                        boolean[] canEdit = new boolean [] {
                                false, true, false, true
                        };

                        public Class getColumnClass(int columnIndex) {
                                return types [columnIndex];
                        }

                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                                return canEdit [columnIndex];
                        }
                });
                jScrollPane1.setViewportView(tabelBimbing);

                konfirmCheckbox.setText("Konfirmasi Pembimbing");
                konfirmCheckbox.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                konfirmCheckboxActionPerformed(evt);
                        }
                });

                btn_simpan.setText("SIMPAN");
                btn_simpan.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btn_simpanActionPerformed(evt);
                        }
                });

                btn_logout.setText("LOGOUT");
                btn_logout.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btn_logoutActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btn_simpan)
                                                .addGap(18, 18, 18)
                                                .addComponent(btn_logout))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGap(24, 24, 24)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(konfirmCheckbox)
                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(nidnLabel)
                                                        .addComponent(namaDosenLabel)
                                                        .addComponent(mahasiswaLabel))))
                                .addContainerGap(25, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(nidnLabel)
                                .addGap(6, 6, 6)
                                .addComponent(namaDosenLabel)
                                .addGap(18, 18, 18)
                                .addComponent(mahasiswaLabel)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(konfirmCheckbox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btn_simpan)
                                        .addComponent(btn_logout))
                                .addGap(74, 74, 74))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void konfirmCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_konfirmCheckboxActionPerformed
        // TODO add your handling code here:
        if(konfirmCheckbox.isSelected()){
        }
        else{
        }
    }//GEN-LAST:event_konfirmCheckboxActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        new login_user().setVisible(true);
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        JOptionPane.showMessageDialog(null,"data tersimpan");
    }//GEN-LAST:event_btn_simpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameDospem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameDospem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameDospem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameDospem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameDospem().setVisible(true);
            }
        });
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btn_logout;
        private javax.swing.JButton btn_simpan;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JCheckBox konfirmCheckbox;
        private javax.swing.JLabel mahasiswaLabel;
        private javax.swing.JLabel namaDosenLabel;
        private javax.swing.JLabel nidnLabel;
        private javax.swing.JTable tabelBimbing;
        // End of variables declaration//GEN-END:variables



    public User getUser() {
        return user;
    }
    public void setUser(User user) {
        this.user = user;
    }
    public Dosen getDosen() {
        return dosen;
    }
    public void setDosen(Dosen dosen) {
        this.dosen = dosen;
    }
    public KerjaPraktek getKerjaPraktek() {
        return kerjaPraktek;
    }
    public void setKerjaPraktek(KerjaPraktek kerjaPraktek) {
        this.kerjaPraktek = kerjaPraktek;
    }
    public Mahasiswa getMahasiswa() {
        return mahasiswa;
    }
    public void setMahasiswa(Mahasiswa mahasiswa) {
        this.mahasiswa = mahasiswa;
    }
    public PersetujuanDosen getPersetujuanDosen() {
        return persetujuanDosen;
    }

    public void setPersetujuanDosen(PersetujuanDosen persetujuanDosen) {
        this.persetujuanDosen = persetujuanDosen;
    }
    public PersetujuanProdi getPersetujuanProdi() {
        return persetujuanProdi;
    }

    public void setPersetujuanProdi(PersetujuanProdi persetujuanProdi) {
        this.persetujuanProdi = persetujuanProdi;
    }

    public Bimbingan getbimbingan() {
        return bimbingan;
    }

    public void setBimbingan(Bimbingan bimbingan) {
        this.bimbingan = bimbingan;
    }
    
     public void getPersetujuanFromDatabase(){
        DefaultTableModel modelTablePersetujuan = (DefaultTableModel) tabelBimbing.getModel();
        modelTablePersetujuan.setRowCount(0);
        Object[] atributKerjaPraktek = new Object[2];
        try {
            ArrayList PersetujuanDosenAll = new KerjaPraktek().semuaDB();
            Iterator listRevisi = PersetujuanDosenAll.iterator();
            while(listRevisi.hasNext()){
                KerjaPraktek eachKerjaPraktek;
                eachKerjaPraktek = (KerjaPraktek) listRevisi.next();
                atributKerjaPraktek[0] = eachKerjaPraktek.mahasiswa.getnama();
                atributKerjaPraktek[1] = eachKerjaPraktek.mahasiswa.getnim();
                atributKerjaPraktek[2] = eachKerjaPraktek.getnamaKegiatan();
                atributKerjaPraktek[3] = eachKerjaPraktek.getinstansi();
        
                modelTablePersetujuan.addRow(atributKerjaPraktek);
            }
            tabelBimbing.setModel(modelTablePersetujuan);
        } catch (Exception ex) {
            Logger.getLogger(FrameDoswal.class.getName()).log(Level.SEVERE, null, ex);
        }

     }
}