/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui_fp;

import codingan.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.*;
/**
 *
 * @author renol
 */
public class status_kp_mhs extends javax.swing.JFrame {

	 Mahasiswa oi  = new Mahasiswa();
 

    /**
     * Creates new form data_mhs_tbl
     */
    public status_kp_mhs() {
        initComponents();
       
        setLocationRelativeTo(this);
    }  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane5 = new javax.swing.JScrollPane();
        tabelKP = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        exit2 = new javax.swing.JButton();
        view1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cekbox2 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelKP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAMA", "NIM", "SEMESTER", "INSTANSI KP", "STATUS", "DOSPEM"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tabelKP);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 760, 140));

        jLabel2.setFont(new java.awt.Font("Sitka Heading", 1, 36)); // NOI18N
        jLabel2.setText("INFORMASI KERJA PRAKTEK");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, 40));

        exit2.setBackground(new java.awt.Color(0, 102, 153));
        exit2.setFont(new java.awt.Font("Sitka Heading", 1, 18)); // NOI18N
        exit2.setText("EXIT");
        exit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit2ActionPerformed(evt);
            }
        });
        getContentPane().add(exit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, 200, 40));

        view1.setBackground(new java.awt.Color(0, 102, 153));
        view1.setFont(new java.awt.Font("Sitka Heading", 1, 18)); // NOI18N
        view1.setText("VIEW");
        view1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view1ActionPerformed(evt);
            }
        });
        getContentPane().add(view1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 210, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar1/d3.jpg"))); // NOI18N
        jLabel1.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 500));

        cekbox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekbox2ActionPerformed(evt);
            }
        });
        getContentPane().add(cekbox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit2ActionPerformed
        info_prodi oii = new info_prodi();  
        oii.setVisible(true);		// PINDAH JFRAME 
        this.setVisible(false);
    }//GEN-LAST:event_exit2ActionPerformed

    private void cekbox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekbox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cekbox2ActionPerformed

        private void view1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view1ActionPerformed
            // MENAMPILKAN INFORMASI KERJA PRAKTEK MELALUI DATABASE
		
	    Mahasiswa oi  = new Mahasiswa();	     
	    DefaultTableModel modelTableStatus = (DefaultTableModel) tabelKP.getModel();
	    modelTableStatus.setRowCount(0);
            Object[] atributPer = new Object[7];
	
        try {
            ArrayList MahasiswaAll = oi.viewAll(); //harus dikasih try catch
            Iterator listPersetujuan = MahasiswaAll.iterator();
            int i = 0;
	    while(i < MahasiswaAll.size()){  // PERULANGAN
                Mahasiswa eachStatus;
                eachStatus = (Mahasiswa) listPersetujuan.next();
                atributPer[0] = eachStatus.getNama(); // MENAMPILKAN NAMA DARI CLASS MAHASISWA (database)
                atributPer[1] = eachStatus.getNim(); // MENAMPILKAN NIM DARI CLASS MAHASISWA (database)
                atributPer[2] = eachStatus.getSemester(); // MENAMPILKAN SEM DARI CLASS MAHASISWA (database)
                atributPer[3] = eachStatus.getinstansi();  // MENAMPILKAN INSTANSI DARI CLASS MAHASISWA (database)
		atributPer[4] = eachStatus.getpersetujuan(); // MENAMPILKAN PERSETUJUAN DARI CLASS MAHASISWA (database)
                modelTableStatus.addRow(atributPer);
		
		i++;
        }
            tabelKP.setModel(modelTableStatus);
        } catch (Exception ex) {
            Logger.getLogger(status_kp_mhs.class.getName()).log(Level.SEVERE, null, ex);
        }
        }//GEN-LAST:event_view1ActionPerformed
   public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new status_kp_mhs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cekbox2;
    private javax.swing.JButton exit2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tabelKP;
    private javax.swing.JButton view1;
    // End of variables declaration//GEN-END:variables
}
